# Generated by Django 5.1.3 on 2024-12-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_notificationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetable',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
