# Generated by Django 5.1.3 on 2024-12-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_feedback_date_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='date',
        ),
        migrations.AddField(
            model_name='complaints',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
