# Generated by Django 5.1.4 on 2025-02-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_addandmanagemembers_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventimage', models.FileField(blank=True, null=True, upload_to='eventimage')),
                ('eventdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('eventID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.event')),
            ],
        ),
        migrations.DeleteModel(
            name='ratingclass',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='USER',
            new_name='event',
        ),
        migrations.DeleteModel(
            name='servicetable',
        ),
    ]
