# Generated by Django 5.1.3 on 2024-12-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_remove_complaints_date_complaints_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='addstudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructions',
            name='date',
        ),
        migrations.AddField(
            model_name='instructions',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now_add=True, default='2014-12-21'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
