# Generated by Django 5.1.3 on 2024-12-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_addstudents_remove_instructions_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
        migrations.AddField(
            model_name='notificationtable',
            name='reply',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='notificationtable',
            name='time',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
