# Generated by Django 5.1.3 on 2024-12-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_delete_notification_notificationtable_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtable',
            name='time',
        ),
        migrations.AlterField(
            model_name='notificationtable',
            name='date',
            field=models.DateField(auto_now_add=True, default='2014-12-12'),
            preserve_default=False,
        ),
    ]
